### ISSUE TITLE
无法运行,提示malloc(): Out of memory

### ISSUE THREAD

**Issue by wwbfred** [mmmdbybyd/CLNC#10]
0.7版本直接命令行运行"./arm64 -c .",提示malloc(): Out of memory.
0.6版本32位没有报错,但实际上并没有启动成功,指定的监听端口没有任何服务.

**Comment by mmmdbybyd** [comment]
你模式名呢

**Comment by wwbfred** [comment]
模式名?你是说用的哪个androidScript么?
我是想把它作为一个单纯的后端服务启动,不需要iptables之类的规则,我是直接命令行运行的.
如果我理解错了我可以贴上我的配置文件,这是我唯一输入的信息.
[clnc.txt](https://github.com/mmmdbybyd/CLNC/files/5197598/clnc.txt)

**Comment by mmmdbybyd** [comment]
作为服务器  你有什么需求吗    如果特殊的话加我qq915445800

**Comment by wwbfred** [comment]
要说特殊也不是,就是多级转发iptables之类的规则已经写好了,这个服务起来就可以直接用了这样.请问可以确定是哪里的问题么?
