### ISSUE TITLE
咋用啊，是直接改后缀名为apk吗 

### ISSUE THREAD

**Issue by Villareally** [mmmdbybyd/CLNC#11]
咋用啊，是直接改后缀名为apk吗

**Comment by mmmdbybyd** [comment]
跟其他脚本防跳差不多的方法，mt管理器解压到/data，然后权限全满    配置config.ini  执行开启

**Comment by Villareally** [comment]
> 跟其他脚本防跳差不多的方法，mt管理器解压到/data，然后权限全满 配置config.ini 执行开启

能用了能用了，太感谢了大佬
