### ISSUE TITLE
禁用ipv6问题

### ISSUE THREAD

**Issue by XiaoHb233** [mmmdbybyd/CLNC#13]
联通王卡clnc  ☞ipv6问题
MIUI12系统和一些魔改系统不能修改或者无效改apn接入点，无法禁用ipv6。
有没有其他办法禁用ipv6或者更新一个只有ipv4的防跳，不知道是不是ipv6问题，京东和某些app网速很慢刷新不了  。
star star★★★★★

**Comment by mmmdbybyd** [comment]
防跳已更新
