### ISSUE TITLE
clnc.conf.forward_v2ray_ssr_nginx共用端口后部分app推送无法即时更新

### ISSUE THREAD

**Issue by 1978245715** [mmmdbybyd/CLNC#16]
比如微信，别人发消息过来，需要等很久才会推送消息（这个很久时间随机），或者只有打开微信APP界面才能收到消息
当切换到非共用的端口，可以即时收到消息

**Comment by 1978245715** [comment]
测试了一次，发送后一般需要3分钟之后才能收到消息

**Comment by mmmdbybyd** [comment]
用的ssr还是什么

**Comment by 1978245715** [comment]
ssr跟v2都有用，都试了，无论脚本版还是软件版都有延迟的情况

**Comment by mmmdbybyd** [comment]
加我QQ看看具体是怎么配置的吧 915445800
