### ISSUE TITLE
执行脚本会Warning: dns::Global keyword [cacheLimit] invalid

### ISSUE THREAD

**Issue by azsummer** [mmmdbybyd/CLNC#17]
开启后会显示Warning: dns::Global keyword [cacheLimit] invalid
之前的版本没有这个

**Comment by ghost** [comment]
> 开启后会显示Warning: dns::Global keyword [cacheLimit] invalid
> 之前的版本没有这个

删掉模式配置文件中cacheLimit那行即可，无关紧要
