### ISSUE TITLE
可不可以将王卡动态接口放到clnc.conf配置文件里，这样可以用王卡动态插卡路由器

### ISSUE THREAD

**Issue by leebook** [mmmdbybyd/CLNC#19]
试过百度可以，王卡动态不好搞

**Comment by mmmdbybyd** [comment]
插卡路由是arm还是什么

**Comment by leebook** [comment]
> 插卡路由是arm还是什么

大佬回复了，好激动。是arm，一般动态都是脚本获取接口验证，脚本一般都是手机版的，路由器运行不了，如果二进制运行clnc核心，没有写动态接口的地方，百度和阿里是静态的所以能行。还有大佬cns有没有使用方法。

**Comment by leebook** [comment]
> 插卡路由是arm还是什么

**Comment by leebook** [comment]
大佬有没有群组呢，想学一下cns使用
