### ISSUE TITLE
王卡动态cns

### ISSUE THREAD

**Issue by XiaoHb233** [mmmdbybyd/CLNC#22]
王卡动态udp部分，填入cns没有网，是不是还要改什么

**Comment by mmmdbybyd** [comment]
之前发的模式错了   用新版的

**Comment by ghost** [comment]
> 之前发的模式错了 用新版的

百度直连tun搜狗输入法表情包加载不出，农行登录不上，还有少部分网页提示error，已添加cns配置，游戏能联网，问下是百度直连服务器问题还是其他原因

**Comment by mmmdbybyd** [comment]
百度问题
