### ISSUE TITLE
脚本核心问题

### ISSUE THREAD

**Issue by chenkid999** [mmmdbybyd/CLNC#25]
请问clnc_local0.5.2.zip里的核心和Releases里的核心有什么区别吗？脚本里自带的核心架构和Releases里的好像都不一样。

**Comment by chenkid999** [comment]
还有一个问题，我使用ssr开分应用代理可以正常代理，v2ray使用分应用代理却会出现无法连接网络的情况，这是没有做适配吗

**Comment by mmmdbybyd** [comment]
脚本里的多了王卡动态，其他没有区别
至于v2 ssr这个按理说是同样的处理

**Comment by chenkid999** [comment]
> 脚本里的多了王卡动态，其他没有区别
> 至于v2 ssr这个按理说是同样的处理

了解，回头我再试试这两个分应用代理的具体情况
