### ISSUE TITLE
想问下同端口分流

### ISSUE THREAD

**Issue by Villareally** [mmmdbybyd/CLNC#26]
同端口分流v2 ssr nginx，这个可以直接复制到 clnc_bd.conf里使用吗。
想实现分流和免流一起

**Comment by mmmdbybyd** [comment]
不可以   这个挺麻烦的

**Comment by Villareally** [comment]
> 不可以 这个挺麻烦的

好吧，我发现正常使用ssr可以开，v2ray和trojan都开了就没网
