### ISSUE TITLE
clncNatShare

### ISSUE THREAD

**Issue by oj8k** [mmmdbybyd/CLNC#27]
root@OpenWrt:~# sh /etc/clnc/start.sh
Illegal instruction
✄┄ ┄ ┄ ┄ ┄ ┄ ┄ ┄ ┄ ┄ ┄ ┄ ┄ ┄
grep: clnc.pid: No such file or directory
✘  clnc 没有运行
✄┄ ┄ ┄ ┄ ┄ ┄ ┄ ┄ ┄ ┄ ┄ ┄ ┄ ┄
root@OpenWrt:~#

**Comment by mmmdbybyd** [comment]
这个用le版本应该就可以，比如：执行uname -m显示mips就用mipsle

**Comment by qw124838** [comment]
clncNatShare，路由器op系统刷入成功，现在IP是百度直连IP，不过cns没有成功代理udp，clnc_bd.conf里面设置了cns，手动生成了clnc_cns.conf，还是不行。自己手机模块里面cns代理正常，看还是很久之前更新的，0.4版本clncNatShare，大佬有空看看啥问题吗 #

**Comment by mmmdbybyd** [comment]
这个是不支持udp的，是传统的nat防跳，目的是解决一些不支持tun防跳的设备
