### ISSUE TITLE
4G openwrt路由跑clnc没网络

### ISSUE THREAD

**Issue by snowicepeng** [mmmdbybyd/CLNC#29]
root@OpenWrt:~/clnc# ./status.sh
./Core/CuteBi: line 1: getenforce: not found
./Core/CuteBi: line 200: setenforce: not found
lo127.0.0.1/8
lo::1/128
eth2192.168.0.100/24
eth2fe80::20c:29ff:fea3:9b6d/64
br-lan192.168.10.1/24
br-lanfd08:5042:820e::1/60
br-lanfe80::2a2c:2ff:fe20:66ae/64
wlan1fe80::2a2c:2ff:fe20:66ac/64
wlan0fe80::203:7fff:fe12:3456/64
✄┄ ┄ ┄ ┄ ┄ ┄ ┄ ┄ ┄ ┄ ┄ ┄ ┄ ┄

✔  clnc 正在运行

✄┄ ┄ ┄ ┄ ┄ ┄ ┄ ┄ ┄ ┄ ┄ ┄ ┄ ┄
❁ mangle表 PREROUTING链:
-P PREROUTING ACCEPT
✺ mangle表 CLNC_PREROUTING链:
-N CLNC_PREROUTING
❁ nat表 PREROUTING链:
-P PREROUTING ACCEPT
-A PREROUTING -s 192.168.0.0/16 -g CLNC_PREROUTING
-A PREROUTING -m comment --comment "!fw3: Custom prerouting rule chain" -j prerouting_rule
-A PREROUTING -i br-lan -m comment --comment "!fw3" -j zone_lan_prerouting
-A PREROUTING -i eth1 -m comment --comment "!fw3" -j zone_wan_prerouting
-A PREROUTING -i eth2 -m comment --comment "!fw3" -j zone_wan_prerouting
✺ nat表 CLNC_PREROUTING链:
-N CLNC_PREROUTING
-A CLNC_PREROUTING -d 8.8.8.8/32 -j ACCEPT
-A CLNC_PREROUTING -d 10.0.0.0/8 -j ACCEPT
-A CLNC_PREROUTING -p udp -m udp --dport 53 -j REDIRECT --to-ports 6653
-A CLNC_PREROUTING ! -d 192.168.0.0/16 -p tcp -j REDIRECT --to-ports 6650
❁ mangle表 FORWARD链:
-P FORWARD ACCEPT
-A FORWARD -g CLNC_FORWARD
-A FORWARD -o eth1 -p tcp -m tcp --tcp-flags SYN,RST SYN -m comment --comment "!fw3: Zone wan MTU fixing" -j TCPMSS --clamp-mss-to-pmtu
-A FORWARD -i eth1 -p tcp -m tcp --tcp-flags SYN,RST SYN -m comment --comment "!fw3: Zone wan MTU fixing" -j TCPMSS --clamp-mss-to-pmtu
-A FORWARD -o eth2 -p tcp -m tcp --tcp-flags SYN,RST SYN -m comment --comment "!fw3: Zone wan MTU fixing" -j TCPMSS --clamp-mss-to-pmtu
-A FORWARD -i eth2 -p tcp -m tcp --tcp-flags SYN,RST SYN -m comment --comment "!fw3: Zone wan MTU fixing" -j TCPMSS --clamp-mss-to-pmtu
✺ mangle表 CLNC_FORWARD链:
-N CLNC_FORWARD
-A CLNC_FORWARD -d 8.8.8.8/32 -j ACCEPT
-A CLNC_FORWARD -d 10.0.0.0/8 -j ACCEPT
-A CLNC_FORWARD ! -d 192.168.0.0/16 -j DROP
./Core/CuteBi: line 223: setenforce: not found

**Comment by mmmdbybyd** [comment]
是停机卡吗？把这一行加在开启脚本后面看看
iptables -t mangle -D FORWARD ! -d 192.168.0.0/16 -j DROP

**Comment by snowicepeng** [comment]
> 是停机卡吗？把这一行加在开启脚本后面看看 iptables -t mangle -D FORWARD ! -d 192.168.0.0/16 -j DROP

我是正常的联通阿里小宝卡，自己搞了个openwrt的4G路由，想跑clnc的uc模式。固件是我自己编译的，已经集成kmod-tun_4.14.254-1_mips_24kc.ipk

**Comment by snowicepeng** [comment]
使用CLNC/androidScript/clnc0.9.2.zip，Core使用Release CLNC1.0 linux_mips，日志如下：
--------------------------------------------
./start.sh
--------------------------------------------
iptables v1.8.3 (legacy): unknown option "--set-xmark"
Try `iptables -h' or 'iptables --help' for more information.
ip6tables v1.8.3 (legacy): unknown option "--set-xmark"
Try `ip6tables -h' or 'ip6tables --help' for more information.
iptables v1.8.3 (legacy): Couldn't load match `connmark':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.
ip6tables v1.8.3 (legacy): Couldn't load match `connmark':No such file or directory

Try `ip6tables -h' or 'ip6tables --help' for more information.
iptables v1.8.3 (legacy): unknown option "--set-xmark"
Try `iptables -h' or 'iptables --help' for more information.
ip6tables v1.8.3 (legacy): unknown option "--set-xmark"
Try `ip6tables -h' or 'ip6tables --help' for more information.
iptables v1.8.3 (legacy): Couldn't load match `connmark':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.
ip6tables v1.8.3 (legacy): Couldn't load match `connmark':No such file or directory

Try `ip6tables -h' or 'ip6tables --help' for more information.
iptables v1.8.3 (legacy): Couldn't load match `owner':No such file or directory

Try `iptables -h' or 'iptables --help' for more information.
ip6tables v1.8.3 (legacy): Couldn't load match `owner':No such file or directory

Try `ip6tables -h' or 'ip6tables --help' for more information.
ip: invalid argument 'unreachable' to 'ip'
✄┄ ┄ ┄ ┄ ┄ ┄ ┄ ┄ ┄ ┄ ┄ ┄ ┄ ┄
./Core/CuteBi: line 283: svc: not found
✔  clnc 正在运行
✄┄ ┄ ┄ ┄ ┄ ┄ ┄ ┄ ┄ ┄ ┄ ┄ ┄ ┄
sleep: invalid number '0.2'
./Core/CuteBi: line 285: svc: not found

--------------------------------------------
./status.sh
--------------------------------------------
lo127.0.0.1/8
lo::1/128
eth2192.168.0.100/24
eth2fe80::20c:29ff:fea3:9b6d/64
br-lan192.168.10.1/24
br-lanfd08:5042:820e::1/60
br-lanfe80::2a2c:2ff:fe20:66ae/64
wlan1fe80::2a2c:2ff:fe20:66ac/64
wlan0fe80::203:7fff:fe12:3456/64
tunDev26.26.26.1/24
tunDevfc00::1/64
tunDevfe80::cd7e:5884:3d6:b138/64
✄┄ ┄ ┄ ┄ ┄ ┄ ┄ ┄ ┄ ┄ ┄ ┄ ┄ ┄

✔  clnc 正在运行

✄┄ ┄ ┄ ┄ ┄ ┄ ┄ ┄ ┄ ┄ ┄ ┄ ┄ ┄
❁ ipv4 mangle表 PREROUTING链:
-P PREROUTING ACCEPT
-A PREROUTING ! -i tun+ -g TUN_PREROUTING
✺ ipv4 mangle表 TUN_PREROUTING链:
-N TUN_PREROUTING
-A TUN_PREROUTING -m conntrack --ctstate INVALID -j DROP
❁ ipv4 filter表 FORWARD链:
-P FORWARD DROP
-A FORWARD -o tun+ -j ACCEPT
-A FORWARD -i tun+ -j ACCEPT
-A FORWARD -m comment --comment "!fw3: Custom forwarding rule chain" -j forwarding_rule
-A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -m comment --comment "!fw3" -j ACCEPT
-A FORWARD -i br-lan -m comment --comment "!fw3" -j zone_lan_forward
-A FORWARD -i eth1 -m comment --comment "!fw3" -j zone_wan_forward
-A FORWARD -i eth2 -m comment --comment "!fw3" -j zone_wan_forward
-A FORWARD -m comment --comment "!fw3" -j reject
✺ ipv4 mangle表 OUTPUT链:
-P OUTPUT ACCEPT
❁ ipv4 mangle表 TUN_OUTPUT链:
-N TUN_OUTPUT
-A TUN_OUTPUT -o wlan+ -j ACCEPT
-A TUN_OUTPUT -o tun+ -j ACCEPT

✄┄ ┄ ┄ ┄ ┄ ┄ ┄ ┄ ┄ ┄ ┄ ┄ ┄ ┄
❁ ipv6 mangle表 PREROUTING链:
-P PREROUTING ACCEPT
-A PREROUTING ! -i tun+ -g TUN_PREROUTING
✺ ipv6 mangle表 TUN_PREROUTING链:
-N TUN_PREROUTING
-A TUN_PREROUTING -m conntrack --ctstate INVALID -j DROP
❁ ipv6 filter表 FORWARD链:
-P FORWARD DROP
-A FORWARD -o tun+ -j ACCEPT
-A FORWARD -i tun+ -j ACCEPT
-A FORWARD -m comment --comment "!fw3: Custom forwarding rule chain" -j forwarding_rule
-A FORWARD -m conntrack --ctstate RELATED,ESTABLISHED -m comment --comment "!fw3" -j ACCEPT
-A FORWARD -i br-lan -m comment --comment "!fw3" -j zone_lan_forward
-A FORWARD -i eth1 -m comment --comment "!fw3" -j zone_wan_forward
-A FORWARD -i eth2 -m comment --comment "!fw3" -j zone_wan_forward
-A FORWARD -m comment --comment "!fw3" -j reject
✺ ipv6 mangle表 OUTPUT链:
-P OUTPUT ACCEPT
❁ ipv6 mangle表 TUN_OUTPUT链:
-N TUN_OUTPUT
-A TUN_OUTPUT -o wlan+ -j ACCEPT
-A TUN_OUTPUT -o tun+ -j ACCEPT

作者能否提供一个可用的版本

**Comment by snowicepeng** [comment]
我路由器现在的路由表
![image](https://user-images.githubusercontent.com/1950551/141427084-30e77a9e-6a57-4ddb-b925-10a5b27a1cf0.png)

**Comment by mmmdbybyd** [comment]
你的路由器不支持打标记，可以考虑用nat的版本

**Comment by mmmdbybyd** [comment]
有的设备去web页面，把路由转发打开可以解决（当然也可以用shell命令把转发打开）
