### ISSUE TITLE
求电信停机卡配置文件，一直没有成功，不知道哪里问题

### ISSUE THREAD

**Issue by ChinaParrot** [mmmdbybyd/CLNC#30]
![1](https://user-images.githubusercontent.com/14269139/142418634-5524a110-ebe5-4b99-b47d-178f73abce9b.png)

**Comment by ChinaParrot** [comment]
tcpProxy::https_proxy {
    //HTTPS代理地址
    destaddr = 112.80.255.21:443;
    tunnelHttpMod = tunnel;
    tunnel_proxy = on;
}

**Comment by mmmdbybyd** [comment]
你参考一下：
广东电信停机
gd.189.cn
path：/TS/recharge/tzUrl.html

**Comment by mmmdbybyd** [comment]
配置一下cns请求头的host和path就可以了
