### ISSUE TITLE
关于encrypt的问题

### ISSUE THREAD

**Issue by mengshouer** [mmmdbybyd/CLNC#31]
我照着免流的配置文件改，如果自己的CNS设置了encrypt_password

tcpProxy::https_proxy的httpMod为tunnel有encrypt的设置项，客户端能正常访问https

但是我看tcpProxy::http_proxy的httpMod为http，设置encrypt和tunnel_encrypt对http的不生效，所以客户端http无网络，好像还会弹出需要认证。请问有额外的配置项吗。翻了翻clncConfig.explain没找到类似的选项

还有udp的服务端是要额外搭建的吗，还是直接使用cns服务的端口就行了？

**Comment by mmmdbybyd** [comment]
http、https、dns、udp全部都用tunnel(CONNECT)的方式连接cns就可以
http直接以https的方式代理

**Comment by mengshouer** [comment]
set_first = "[M] http://[H_P][U] [V]\r\nHost: [H_P]\r\nX-T5-Auth: 1967948331\r\n";
这个http的set_firest没影响吗

**Comment by mmmdbybyd** [comment]
影响，你直接把http的tcpAcl删了，让https的tcpAcl把所有流量判断为https就可以

**Comment by mengshouer** [comment]
暂时没啥问题了
