### ISSUE TITLE
为clnc设置二级代理

### ISSUE THREAD

**Issue by Muffeter** [mmmdbybyd/CLNC#32]
思路：客户端数据->clnc->vpn->服务器

看了看doc
发现

> [socks5_client = on/username password]，程序作为socks5客户端，发送出去的数据使用一层socks5代理，如果需要使用用户名密码，则将on替换为用户名密码，用户名跟密码之间用一个空格隔开

1.此处的作为socks5客户端是否有误，是否为socks服务端？
2.如何为clnc设置二级代理

**Comment by mmmdbybyd** [comment]
此处是发出去的   如果需要VPN代理clnc，防跳放行VPN的app，clnc转发socks5到VPN，不过clnc不支持接收UDP然后转为UDP的socks5
