### ISSUE TITLE
clnc.conf.ml的dns设置问题

### ISSUE THREAD

**Issue by JamesLiu0802** [mmmdbybyd/CLNC#33]
在使用时发现部分域名无法解析，该怎么修改默认的dns设置。

**Comment by JamesLiu0802** [comment]
解决了域名解析问题，引起域名解析失败的原因是域名大写。

**Comment by JamesLiu0802** [comment]
不知能否解决一下，域名大写时无法解析的问题？如果域名包含数字，则解析成功；而只有大写字母的域名无法解析。

**Comment by mmmdbybyd** [comment]
更新了脚本  你看看

**Comment by JamesLiu0802** [comment]
![image](https://user-images.githubusercontent.com/86506347/162552042-1d7b7494-2b5f-4329-99d4-bd96c09da74f.png)
好像还是不行，不知道什么原因。

**Comment by JamesLiu0802** [comment]
百度直连封了端口后，现在不能用cns了吗？检测udp联网全都是失败。

**Comment by mmmdbybyd** [comment]
这个是腾讯的HTTPDNS问题，他的HTTPDNS不支持大写，需要核心改为小写才可以，我今晚改一下

**Comment by JamesLiu0802** [comment]
好的，谢谢。

**Comment by JamesLiu0802** [comment]
udp检测可以了，我搞错了cns地址，差点给大佬造成麻烦了。（可能是因为端口封了的原因，v2rayng或者clash用分应用代理还是无法直接代理）
