### ISSUE TITLE
tcpProxy模块是否可以像httpUDP一样使用CNS作为二级代理呢？

### ISSUE THREAD

**Issue by gaoadmin** [mmmdbybyd/CLNC#34]
tcpProxy模块是否可以像httpUDP一样使用CNS作为二级代理呢？

**Comment by mmmdbybyd** [comment]
这个可以，只是配置太繁琐了，不推荐
流程是：用clnc转为CONNECT -> 用clnc将CONNECT转为socks5发送到clnc自身 -> clnc再生成一次CONNECT发送到一级代理 -> 一级代理转发流量到作为二级代理的CNS
