### ISSUE TITLE
debian系统的使用问题

### ISSUE THREAD

**Issue by dhz110** [mmmdbybyd/CLNC#36]
我的棒子刷了debian系统，然后把你的包下载下来后需要配置什么吗，还是直接启动start.sh吗

**Comment by mmmdbybyd** [comment]
按理说是没什么问题的

**Comment by dhz110** [comment]
可以了，是debian没有安装busybox和ip2
问题解决过了，谢谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月1日(周四) 下午3:48
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [mmmdbybyd/CLNC] debian系统的使用问题 (Issue #36)




 
按理说是没什么问题的
