### ISSUE TITLE
建议王卡动态clnc增加自定义接口配置

### ISSUE THREAD

**Issue by dollarser** [mmmdbybyd/CLNC#4]
昨天开始王卡动态接口失效，由于接口失效，导致无法联网。因为对于没有qq浏览器定向的卡本地抓包不能用，所有接口失效这个就彻底不能用了。

**Comment by Bonnie-Ran** [comment]
附議

**Comment by mmmdbybyd** [comment]
这是我测试其他程序的时候临时关闭服务器，之后忘记开启了，我服务器也可以自动拉取其他接口。不需要自定义
