### ISSUE TITLE
double free or corruption

### ISSUE THREAD

**Issue by papa18** [mmmdbybyd/CLNC#5]
在路由器上执行时，使用socks5代理时报错

root@OpenWrt:~# ./clnc_arm_0.5 -d -c ml.conf 
*** Error in `./clnc_arm_0.5': double free or corruption (fasttop): 0xb3a0f480 ***

路由器架构
ARMv7 Processor rev 5 (v7l) x 4

**Comment by mmmdbybyd** [comment]
下个版本会修复
