### ISSUE TITLE
clnc_王卡(05.10nat).zip的問題

### ISSUE THREAD

**Issue by Bonnie-Ran** [mmmdbybyd/CLNC#6]
dynamic connect() or write(): Connection refused
是端口被占用，還是服務器關閉

**Comment by mmmdbybyd** [comment]
这是我测试其他程序的时候临时关闭服务器，之后忘记开启了，现在已经没问题了

**Comment by Bonnie-Ran** [comment]
OK，早點休息啊，身體重要
