### ISSUE TITLE
clnc-nat-0.5版本與SSR衝突

### ISSUE THREAD

**Issue by Bonnie-Ran** [mmmdbybyd/CLNC#7]
當運行clnc-nat-0.5腳本時，打開SSR軟件，連接SSR節點，會導致無網絡，關閉腳本則不存在這一問題
(老王VPN之類的軟件與腳本不衝突)

**Comment by mmmdbybyd** [comment]
ssr分应用代理

**Comment by Bonnie-Ran** [comment]
> ssr分应用代理

感謝感謝感謝(問題已完美解決)，要是能解決電腦連接手機熱點無網絡問題就完美啦

**Comment by Villareally** [comment]
> > ssr分应用代理
> 
> 感謝感謝感謝(問題已完美解決)，要是能解決電腦連接手機熱點無網絡問題就完美啦

你好，请教下分应用代理是代理的root explore吗？

**Comment by Bonnie-Ran** [comment]
> > > ssr分应用代理
> > 
> > 
> > 感謝感謝感謝(問題已完美解決)，要是能解決電腦連接手機熱點無網絡問題就完美啦
> 
> 你好，请教下分应用代理是代理的root explore吗？

SSR裡面往下滑，有個分應用代理的選項，打開，把你需要代理的軟件選上就可以啦

**Comment by Villareally** [comment]
> > > > ssr分应用代理
> > > 
> > > 
> > > 感謝感謝感謝(問題已完美解決)，要是能解決電腦連接手機熱點無網絡問題就完美啦
> > 
> > 
> > 你好，请教下分应用代理是代理的root explore吗？
> 
> SSR裡面往下滑，有個分應用代理的選項，打開，把你需要代理的軟件選上就可以啦

好的，但是我用脚本了以后，之前能用的就变成无网络连接状态了，代理也没法用了

**Comment by Bonnie-Ran** [comment]
> > > > > ssr分应用代理
> > > > 
> > > > 
> > > > 感謝感謝感謝(問題已完美解決)，要是能解決電腦連接手機熱點無網絡問題就完美啦
> > > 
> > > 
> > > 你好，请教下分应用代理是代理的root explore吗？
> > 
> > 
> > SSR裡面往下滑，有個分應用代理的選項，打開，把你需要代理的軟件選上就可以啦
> 
> 好的，但是我用脚本了以后，之前能用的就变成无网络连接状态了，代理也没法用了

我是腳本平時使用沒有問題，但不分應用代理，直接開SSR就會無網絡，如果你用的tun版本，換一下nat版本試一下，我的tun版本不免，nat正常使用

**Comment by Villareally** [comment]
> > > > > > ssr分应用代理
> > > > > 
> > > > > 
> > > > > 感謝感謝感謝(問題已完美解決)，要是能解決電腦連接手機熱點無網絡問題就完美啦
> > > > 
> > > > 
> > > > 你好，请教下分应用代理是代理的root explore吗？
> > > 
> > > 
> > > SSR裡面往下滑，有個分應用代理的選項，打開，把你需要代理的軟件選上就可以啦
> > 
> > 
> > 好的，但是我用脚本了以后，之前能用的就变成无网络连接状态了，代理也没法用了
> 
> 我是腳本平時使用沒有問題，但不分應用代理，直接開SSR就會無網絡，如果你用的tun版本，換一下nat版本試一下，我的tun版本不免，nat正常使用

好的我明白了，非常感谢大佬的耐心解答「比心」

**Comment by Bonnie-Ran** [comment]
> > > > > > > ssr分应用代理
> > > > > > 
> > > > > > 
> > > > > > 感謝感謝感謝(問題已完美解決)，要是能解決電腦連接手機熱點無網絡問題就完美啦
> > > > > 
> > > > > 
> > > > > 你好，请教下分应用代理是代理的root explore吗？
> > > > 
> > > > 
> > > > SSR裡面往下滑，有個分應用代理的選項，打開，把你需要代理的軟件選上就可以啦
> > > 
> > > 
> > > 好的，但是我用脚本了以后，之前能用的就变成无网络连接状态了，代理也没法用了
> > 
> > 
> > 我是腳本平時使用沒有問題，但不分應用代理，直接開SSR就會無網絡，如果你用的tun版本，換一下nat版本試一下，我的tun版本不免，nat正常使用
> 
> 好的我明白了，非常感谢大佬的耐心解答「比心」

不是大佬啦，沒事呢，我也是摸索加別人給我解釋過來的，你下載那個源碼zip文件，裡面有好多版本的腳本，多試幾個，應該可以正常使用的

**Comment by mmmdbybyd** [comment]
ssr配合tun确实没试过 不知道规则有没有问题。至于共享崩溃，目前已找到一个原因，但是还有不崩溃但是无网的问题  还在查找

**Comment by Bonnie-Ran** [comment]
> ssr配合tun确实没试过 不知道规则有没有问题。至于共享崩溃，目前已找到一个原因，但是还有不崩溃但是无网的问题 还在查找

最近幾天跳點突然變得很高，以前基本不跳，腳本沒動過，是手機環境問題嘛
